server:
#  ip: 101.43.208.178
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj?serverTimezone=GMT%2b8
    username: root
    password: 111111
mybatis:
  mapper-locations:
    classpath: mapper/*.xml
#  configuration:    # mybatis打印拼接的sql语句日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

spring.mail:
  host: smtp.163.com
  username: sjylearn@163.com
  password: QTIZGXMNPXFJOZBT
  protocol: smtp
  port: 25
  default-encoding: utf-8
  properties:
    mail:
      debug: true #打印日志

# 项目相关配置
oj:
  # 名称
  name: Online Judge
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022
  # 头像上传
  avatar: E:\\oj\\avatar\\
  #jar
#  avatar: /home/server/oj/avatar/
  # 配置邮箱验证的地址（打包时需要更改为服务器的外网ip）
  email: http://localhost:3000
  #服务器ip（存文件）
  serverIp: http://localhost
  #jar
#  email: http://101.43.208.178
#  serverIp: http://101.43.208.178
